### ISSUE TITLE
The relayer '*' could not be found

### ISSUE THREAD

**Issue by gaia** [SimplyVC/eth-block-proposal-monitor#1]
Saw the presentation on the Lido call. Looking forward to testing this out!

```Traceback (most recent call last):
  File "/home/ubuntu/eth-block-proposal-monitor/src/main.py", line 836, in <module>
    insert_new_slot(data['slot'], data['proposer'], data['relay'], data['missed'], data['empty'], reward)
  File "/home/ubuntu/eth-block-proposal-monitor/src/db_ops.py", line 146, in insert_new_slot
    raise Exception("The relayer '"+relayer+"' could not be found. Please update your relay config and try again.")
Exception: The relayer 'Blocknative' could not be found. Please update your relay config and try again.```

Next time I run it, it will give an error about a different relayer (`The relayer 'ultra sound' could not be found`).

`pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)`
`commit 34d34cfab7611442696dbef0cbda8d7040815a6a (HEAD -> main, origin/main, origin/HEAD)`

Not running under a dedicated user, but it is an unprivileged user (standard `ubuntu` user). it's already isolated inside it's own LXD/LXC container.

**Comment by frangrech** [comment]
Hi, could you try deleting the slot_data.db file located in /eth-block-proposal-monitor/data/ and running the script again? On the first run, and on the creation of the database, it should populate the relayers table using the relay_config.json that should be located in /eth-block-proposal-monitor/config/.

**Comment by gaia** [comment]
thanks, fran! that did it.

_small suggestion_: if `/etc/systemd/system/eth2_block_monitoring.service` already exists, do not overwrite it when running the script again. ppl customize it, it's best to not overwrite. if the user needs it rebuild, they can simply delete it.
