### ISSUE TITLE
Beacon Node Request Failed

### ISSUE THREAD

**Issue by gaia** [SimplyVC/eth-block-proposal-monitor#2]
Getting `Request failed: http://192.168.0.56:5052/eth/v2/beacon/blocks/5850051` when running, but `curl -s http://192.168.0.56:5052/eth/v2/beacon/blocks/5850051` yields

`{"code":500,"message":"UNHANDLED_ERROR: BlockHashMissingFromExecutionLayer(0x2681d8e6148d52e244b7b84f0335306d7185f16ffcb9e22d08ce48c442999dd1)","stacktraces":[]}`

IMHO this is not a failed request: there was a reply, just not a satisfactory/usable one. Best to label it as `Request Response Error` or similar.

BTW the error is bc geth was behind/out of sync.

This is only feedback. feel free to close w/o comment. thanks again!

**Comment by frangrech** [comment]
I've changed the wording of the error message in the latest release. When getting slots, in case of an error, we started including the error returned by the endpoint, so that it is clearer for the user why the request failed, or why it did not return the response expected. Will be closing issue.
